CONFIG_AMEBA_NPU=y
CONFIG_AMEBA_NPU_MODEL_FLASH_LOADER=y
CONFIG_AMEBA_NPU_YOLOV4_TINY_POSTPROCESS=y
CONFIG_AMEBA_NPU_SCRFD_POSTPROCESS=y
# CONFIG_AMEBA_NPU_LOG_LEVEL_OFF=y
# CONFIG_AMEBA_NPU_LOG_LEVEL_ERR=y
CONFIG_AMEBA_NPU_LOG_LEVEL_WRN=y
# CONFIG_AMEBA_NPU_LOG_LEVEL_INF=y
# CONFIG_AMEBA_NPU_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=16384
