CONFIG_VIDEO=y

# NPU / live YOLOv4-tiny
CONFIG_AMEBA_NPU=y
CONFIG_AMEBA_NPU_MODEL_FLASH_LOADER=y
CONFIG_AMEBA_NPU_YOLOV4_TINY_POSTPROCESS=y
CONFIG_AMEBA_NPU_LOG_LEVEL_WRN=y
CONFIG_LOG_BUFFER_SIZE=16384

# sd card
CONFIG_DISK_DRIVERS=y
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_EXFAT=y
